// <auto-generated />
using System;
using Devon4Net.WebAPI.Implementation.Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Devon4Net.WebAPI.Implementation.Migrations
{
    [DbContext(typeof(AelContext))]
    [Migration("20210117213203_17012021_Ael_SeedData")]
    partial class _17012021_Ael_SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:Collation", "en_US.utf8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.Tax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TaxDeadlineDate")
                        .HasColumnType("date");

                    b.Property<string>("TaxName")
                        .HasColumnType("character varying");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Taxes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b3293b9-991a-4d2a-991a-1009af56f085"),
                            TaxDeadlineDate = new DateTime(2021, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxName = "ibi",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("cb855976-d21d-42f6-92e7-d0c988b915b1"),
                            TaxDeadlineDate = new DateTime(2022, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxName = "ibi",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("b244e7fe-db00-4191-bffc-b8aab5e0c930"),
                            TaxDeadlineDate = new DateTime(2023, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxName = "ibi",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("1b861525-098a-4acb-ad83-f3a2572cea09"),
                            TaxDeadlineDate = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxName = "vehiculos",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("113a2bc0-78e9-4699-bf5c-db2a14b3e651"),
                            TaxDeadlineDate = new DateTime(2022, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxName = "vehiculos",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("5264fa44-a6a4-4cb7-8c22-772af147a91b"),
                            TaxDeadlineDate = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxName = "vehiculos",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("6f2edd78-9233-43fd-92a8-b3d106b8fcc9"),
                            TaxDeadlineDate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxName = "basura",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("d48716b4-def8-412a-8c9f-6df2f82fad7b"),
                            TaxDeadlineDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxName = "basura",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("620f0961-04aa-4ac7-9882-4372b329eca7"),
                            TaxDeadlineDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaxName = "basura",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.Town", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Community")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("Towns");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef6c18d5-9271-4ca2-97f1-1f99038e1d0a"),
                            Community = " Comunidad Valenciana",
                            TownName = "valencia"
                        },
                        new
                        {
                            Id = new Guid("ef9c2b13-0421-4643-a67e-e62804844640"),
                            Community = " Comunidad Valenciana",
                            TownName = "ademuz"
                        },
                        new
                        {
                            Id = new Guid("39451542-5bbe-458b-a7d7-3efa42298172"),
                            Community = " Comunidad Valenciana",
                            TownName = "ador"
                        },
                        new
                        {
                            Id = new Guid("c8f0d793-575d-4dbe-80f4-baa2457e3875"),
                            Community = " Comunidad Valenciana",
                            TownName = "adzaneta de albaida"
                        },
                        new
                        {
                            Id = new Guid("0179a51d-f88f-4015-915e-d62fd3a0224d"),
                            Community = " Comunidad Valenciana",
                            TownName = "agullent"
                        },
                        new
                        {
                            Id = new Guid("fbee1302-9161-47bc-911b-3b160acdc42f"),
                            Community = " Comunidad Valenciana",
                            TownName = "alacuás"
                        },
                        new
                        {
                            Id = new Guid("791bc3fc-9edd-406b-8e1e-f9cb09cb1a9d"),
                            Community = " Comunidad Valenciana",
                            TownName = "albaida"
                        },
                        new
                        {
                            Id = new Guid("34ebf472-6e43-44e0-b9e4-b9424148062f"),
                            Community = " Comunidad Valenciana",
                            TownName = "albal"
                        },
                        new
                        {
                            Id = new Guid("4cc415d3-6157-4a91-b15a-e073685f20e5"),
                            Community = " Comunidad Valenciana",
                            TownName = "albalat de la ribera"
                        },
                        new
                        {
                            Id = new Guid("54bca052-05a1-459e-9f1c-3a28b5b7e6da"),
                            Community = " Comunidad Valenciana",
                            TownName = "albalat dels sorells"
                        },
                        new
                        {
                            Id = new Guid("3ed070c7-1f8b-454f-bf99-b5868d1a0b69"),
                            Community = " Comunidad Valenciana",
                            TownName = "albalat dels tarongers"
                        },
                        new
                        {
                            Id = new Guid("9d6b86cf-0aef-4fdb-85f6-83b26600525e"),
                            Community = " Comunidad Valenciana",
                            TownName = "alberique"
                        },
                        new
                        {
                            Id = new Guid("ca1290bc-70b2-4358-9db2-fab341ff8b59"),
                            Community = " Comunidad Valenciana",
                            TownName = "alborache"
                        },
                        new
                        {
                            Id = new Guid("411b19b2-3bcc-44a4-a4e2-4335a7765741"),
                            Community = " Comunidad Valenciana",
                            TownName = "alboraya"
                        },
                        new
                        {
                            Id = new Guid("16250800-4258-4999-ad58-aa2c44f2f8ec"),
                            Community = " Comunidad Valenciana",
                            TownName = "albuixech"
                        },
                        new
                        {
                            Id = new Guid("99f50c01-77e6-44f8-a48d-174662a2fd7c"),
                            Community = " Comunidad Valenciana",
                            TownName = "alcácer"
                        },
                        new
                        {
                            Id = new Guid("2dd131ea-aa81-4246-a4f8-7dbaa25f1f9d"),
                            Community = " Comunidad Valenciana",
                            TownName = "alcántara de júcar"
                        },
                        new
                        {
                            Id = new Guid("4b0ced01-4b90-4af6-84be-ab1e40489804"),
                            Community = " Comunidad Valenciana",
                            TownName = "alcira"
                        },
                        new
                        {
                            Id = new Guid("d9ac0e3f-c234-4827-8ec9-7900915904ae"),
                            Community = " Comunidad Valenciana",
                            TownName = "alcublas"
                        },
                        new
                        {
                            Id = new Guid("66caf3e4-fb6d-46f2-acf8-e037a30e5fe9"),
                            Community = " Comunidad Valenciana",
                            TownName = "alcudia de crespins"
                        },
                        new
                        {
                            Id = new Guid("105b7671-fee1-4843-830a-95d0e8d8e478"),
                            Community = " Comunidad Valenciana",
                            TownName = "aldaya"
                        },
                        new
                        {
                            Id = new Guid("975ed7ce-688a-47e4-b54c-4d06f558d278"),
                            Community = " Comunidad Valenciana",
                            TownName = "alfafar"
                        },
                        new
                        {
                            Id = new Guid("984bbc93-3f73-4f08-8928-af2b67fdce40"),
                            Community = " Comunidad Valenciana",
                            TownName = "alfahuir"
                        },
                        new
                        {
                            Id = new Guid("273757c9-8e5f-431e-82af-182d435761be"),
                            Community = " Comunidad Valenciana",
                            TownName = "alfara de la baronía"
                        },
                        new
                        {
                            Id = new Guid("dcfe9cd4-66e7-4bda-b506-708ec59816f4"),
                            Community = " Comunidad Valenciana",
                            TownName = "alfara del patriarca"
                        },
                        new
                        {
                            Id = new Guid("76ac8ff1-630f-40bc-b70c-fd439742c8ea"),
                            Community = " Comunidad Valenciana",
                            TownName = "alfarp"
                        },
                        new
                        {
                            Id = new Guid("7f4498c1-6105-4f52-bc2e-3fda62f5c227"),
                            Community = " Comunidad Valenciana",
                            TownName = "alfarrasí"
                        },
                        new
                        {
                            Id = new Guid("06ba071b-dce5-4877-8d62-e878f39fbec1"),
                            Community = " Comunidad Valenciana",
                            TownName = "algar de palancia"
                        },
                        new
                        {
                            Id = new Guid("b7bd5805-35bc-47c7-a687-f3c5f02f08b9"),
                            Community = " Comunidad Valenciana",
                            TownName = "algemesí"
                        },
                        new
                        {
                            Id = new Guid("68a0479e-c42f-4e91-927f-6fd7522fed98"),
                            Community = " Comunidad Valenciana",
                            TownName = "algimia de alfara"
                        },
                        new
                        {
                            Id = new Guid("1f2b0bfb-2808-4d42-ab69-c37bb1c8ef54"),
                            Community = " Comunidad Valenciana",
                            TownName = "alginet"
                        },
                        new
                        {
                            Id = new Guid("6c259f9b-9f27-480d-9af5-f1d4e9d5abda"),
                            Community = " Comunidad Valenciana",
                            TownName = "almácera"
                        },
                        new
                        {
                            Id = new Guid("ed340c34-6285-4faf-9f14-66f539d50f27"),
                            Community = " Comunidad Valenciana",
                            TownName = "almiserat"
                        },
                        new
                        {
                            Id = new Guid("ae6feeba-293d-48a5-afe3-84b31afa0a19"),
                            Community = " Comunidad Valenciana",
                            TownName = "almoines"
                        },
                        new
                        {
                            Id = new Guid("e3f33976-e9d1-414d-aa31-99e11ab64660"),
                            Community = " Comunidad Valenciana",
                            TownName = "almusafes"
                        },
                        new
                        {
                            Id = new Guid("f1bf088e-2834-4125-a433-b25dc11bb875"),
                            Community = " Comunidad Valenciana",
                            TownName = "alpuente"
                        },
                        new
                        {
                            Id = new Guid("f7e17ef8-9012-4080-a48a-7361e74f284b"),
                            Community = " Comunidad Valenciana",
                            TownName = "alquería de la condesa"
                        },
                        new
                        {
                            Id = new Guid("44f6d13e-0b12-4e1b-859f-2c15f4d1438c"),
                            Community = " Comunidad Valenciana",
                            TownName = "andilla"
                        },
                        new
                        {
                            Id = new Guid("1edec53c-f167-413b-83a7-96d21cf83e59"),
                            Community = " Comunidad Valenciana",
                            TownName = "anna"
                        },
                        new
                        {
                            Id = new Guid("dd5f4e23-a65a-4892-a89a-8fd603e701d6"),
                            Community = " Comunidad Valenciana",
                            TownName = "antella"
                        },
                        new
                        {
                            Id = new Guid("2dabf263-0105-41ca-ac86-d83c35a2ebe4"),
                            Community = " Comunidad Valenciana",
                            TownName = "aras de los olmos"
                        },
                        new
                        {
                            Id = new Guid("ad467f30-775b-45ba-a24a-c925b28fbf29"),
                            Community = " Comunidad Valenciana",
                            TownName = "ayelo de malferit"
                        },
                        new
                        {
                            Id = new Guid("51d93462-c909-40a1-8e7d-ea621b668f15"),
                            Community = " Comunidad Valenciana",
                            TownName = "ayelo de rugat"
                        },
                        new
                        {
                            Id = new Guid("72f85452-a015-4c3c-83fc-bf07116b8ac0"),
                            Community = " Comunidad Valenciana",
                            TownName = "ayora"
                        },
                        new
                        {
                            Id = new Guid("9563d586-8ad0-47af-a2a2-cbe45db23333"),
                            Community = " Comunidad Valenciana",
                            TownName = "barcheta"
                        },
                        new
                        {
                            Id = new Guid("b0e135e0-999a-4a85-8572-ad8515c00c68"),
                            Community = " Comunidad Valenciana",
                            TownName = "bárig"
                        },
                        new
                        {
                            Id = new Guid("bc3df222-99e1-4894-a9d0-a9bbd825c55c"),
                            Community = " Comunidad Valenciana",
                            TownName = "bélgida"
                        },
                        new
                        {
                            Id = new Guid("ed7d0125-7bdf-4767-80e2-2abd0bdd0370"),
                            Community = " Comunidad Valenciana",
                            TownName = "bellreguart"
                        },
                        new
                        {
                            Id = new Guid("9e8f11ac-cd0c-4245-9ce8-bf6e28548e19"),
                            Community = " Comunidad Valenciana",
                            TownName = "bellús"
                        },
                        new
                        {
                            Id = new Guid("2a3fd21d-5482-4f14-b71d-37c54c2dccae"),
                            Community = " Comunidad Valenciana",
                            TownName = "benagéber"
                        },
                        new
                        {
                            Id = new Guid("9bf15731-c016-4c56-925d-40d235405b0f"),
                            Community = " Comunidad Valenciana",
                            TownName = "benaguacil"
                        },
                        new
                        {
                            Id = new Guid("52374818-a511-489a-b266-b94732ce8b8f"),
                            Community = " Comunidad Valenciana",
                            TownName = "benavites"
                        },
                        new
                        {
                            Id = new Guid("3fc6f074-8839-47ff-a4fb-93ae78bd7514"),
                            Community = " Comunidad Valenciana",
                            TownName = "benegida"
                        },
                        new
                        {
                            Id = new Guid("3e84ca30-8778-4db4-847d-e24b0710392b"),
                            Community = " Comunidad Valenciana",
                            TownName = "benetúser"
                        },
                        new
                        {
                            Id = new Guid("a1fa541a-1c15-463c-b13b-8aaa10494dc8"),
                            Community = " Comunidad Valenciana",
                            TownName = "beniarjó"
                        },
                        new
                        {
                            Id = new Guid("8c8dcbd6-94a6-493c-94c4-c5ad93abb700"),
                            Community = " Comunidad Valenciana",
                            TownName = "beniatjar"
                        },
                        new
                        {
                            Id = new Guid("40b1b872-3539-40a5-bfc9-6167e50a148f"),
                            Community = " Comunidad Valenciana",
                            TownName = "benicolet"
                        },
                        new
                        {
                            Id = new Guid("1cc39fd3-c8ee-46aa-87b3-c0fd1f3b154e"),
                            Community = " Comunidad Valenciana",
                            TownName = "benicull"
                        },
                        new
                        {
                            Id = new Guid("7b8e8250-e236-4aeb-8783-06d5c14485fc"),
                            Community = " Comunidad Valenciana",
                            TownName = "benifairó de la valldigna"
                        },
                        new
                        {
                            Id = new Guid("009ae27c-eeba-4a7c-8241-04aafc5980b4"),
                            Community = " Comunidad Valenciana",
                            TownName = "benifairó de los valles"
                        },
                        new
                        {
                            Id = new Guid("43678739-7454-4e2c-ba88-7b4ba9ec053b"),
                            Community = " Comunidad Valenciana",
                            TownName = "benifayó"
                        },
                        new
                        {
                            Id = new Guid("0fe17274-ad68-4945-8fb9-8fbcf514b8cf"),
                            Community = " Comunidad Valenciana",
                            TownName = "beniflá"
                        },
                        new
                        {
                            Id = new Guid("82ac4a12-782b-45e2-b236-51ac92c5689c"),
                            Community = " Comunidad Valenciana",
                            TownName = "benigánim"
                        },
                        new
                        {
                            Id = new Guid("7f071ea8-d035-4a38-bfac-fd381450fa75"),
                            Community = " Comunidad Valenciana",
                            TownName = "benimodo"
                        },
                        new
                        {
                            Id = new Guid("27beb1be-22d9-4fe6-b19f-ea94287d8cbe"),
                            Community = " Comunidad Valenciana",
                            TownName = "benimuslem"
                        },
                        new
                        {
                            Id = new Guid("a8b7e4bb-361b-4fec-b0ca-f7a03d84236a"),
                            Community = " Comunidad Valenciana",
                            TownName = "beniparrell"
                        },
                        new
                        {
                            Id = new Guid("57606c04-38f9-496d-b757-0800df360c60"),
                            Community = " Comunidad Valenciana",
                            TownName = "benirredrá"
                        },
                        new
                        {
                            Id = new Guid("354f03a3-baf0-4dc4-bcce-7195b805c6df"),
                            Community = " Comunidad Valenciana",
                            TownName = "benisanó"
                        },
                        new
                        {
                            Id = new Guid("ec45fc01-d9c5-4f48-8d85-036fea5c3b61"),
                            Community = " Comunidad Valenciana",
                            TownName = "benisoda"
                        },
                        new
                        {
                            Id = new Guid("35fe89c0-02f1-48c3-93a9-fb68b2428c5b"),
                            Community = " Comunidad Valenciana",
                            TownName = "benisuera"
                        },
                        new
                        {
                            Id = new Guid("424fb2a5-418a-46f1-aff8-ca37ea3a3a17"),
                            Community = " Comunidad Valenciana",
                            TownName = "bétera"
                        },
                        new
                        {
                            Id = new Guid("7bcec92e-0673-4dc7-846b-bebd090e30df"),
                            Community = " Comunidad Valenciana",
                            TownName = "bicorp"
                        },
                        new
                        {
                            Id = new Guid("edcd39aa-1376-41c9-b064-6956fc06d99d"),
                            Community = " Comunidad Valenciana",
                            TownName = "bocairente"
                        },
                        new
                        {
                            Id = new Guid("4a4fa7d1-5186-497a-8b14-2a88b72fa7c4"),
                            Community = " Comunidad Valenciana",
                            TownName = "bolbaite"
                        },
                        new
                        {
                            Id = new Guid("3c362f94-e358-45f8-8c68-d091094ba823"),
                            Community = " Comunidad Valenciana",
                            TownName = "bonrepós y mirambell"
                        },
                        new
                        {
                            Id = new Guid("781b1cd8-fd8a-4196-80ca-4e027f62cede"),
                            Community = " Comunidad Valenciana",
                            TownName = "bufali"
                        },
                        new
                        {
                            Id = new Guid("0ab7e7ad-d089-4cb7-afee-ae83e4b7ae9c"),
                            Community = " Comunidad Valenciana",
                            TownName = "bugarra"
                        },
                        new
                        {
                            Id = new Guid("28ac11ee-5ae1-42c9-8650-ec6bb547a0e0"),
                            Community = " Comunidad Valenciana",
                            TownName = "buñol"
                        },
                        new
                        {
                            Id = new Guid("100bf7ce-9d9f-42dc-913a-7cd4269dda74"),
                            Community = " Comunidad Valenciana",
                            TownName = "burjasot"
                        },
                        new
                        {
                            Id = new Guid("903c0f22-7065-4017-abca-ac653b95d986"),
                            Community = " Comunidad Valenciana",
                            TownName = "calles"
                        },
                        new
                        {
                            Id = new Guid("0845b03e-2744-4766-bca7-fa072715ab57"),
                            Community = " Comunidad Valenciana",
                            TownName = "camporrobles"
                        },
                        new
                        {
                            Id = new Guid("a2ece2fc-baf3-433b-95de-4912c6498ae5"),
                            Community = " Comunidad Valenciana",
                            TownName = "canals"
                        },
                        new
                        {
                            Id = new Guid("465277cd-7417-46f1-892f-18f81068f719"),
                            Community = " Comunidad Valenciana",
                            TownName = "canet de berenguer"
                        },
                        new
                        {
                            Id = new Guid("e2413215-0fd2-4cd0-8485-b4ff0111c80c"),
                            Community = " Comunidad Valenciana",
                            TownName = "carcagente"
                        },
                        new
                        {
                            Id = new Guid("500ce6cf-9d86-4502-a932-c265f1caae05"),
                            Community = " Comunidad Valenciana",
                            TownName = "cárcer"
                        },
                        new
                        {
                            Id = new Guid("ec3747f5-716a-4dc9-8535-f6bed43df856"),
                            Community = " Comunidad Valenciana",
                            TownName = "carlet"
                        },
                        new
                        {
                            Id = new Guid("0fb92c02-3e21-4900-838d-355eb17cecf0"),
                            Community = " Comunidad Valenciana",
                            TownName = "carrícola"
                        },
                        new
                        {
                            Id = new Guid("ce876221-89d1-4dc7-9f8b-427ed87aded5"),
                            Community = " Comunidad Valenciana",
                            TownName = "casas altas"
                        },
                        new
                        {
                            Id = new Guid("93c643d7-2a48-48f2-9b2a-9417fe75d71d"),
                            Community = " Comunidad Valenciana",
                            TownName = "casas bajas"
                        },
                        new
                        {
                            Id = new Guid("3bc4a148-d207-40e4-b55e-1e38bf6cb87b"),
                            Community = " Comunidad Valenciana",
                            TownName = "casinos"
                        },
                        new
                        {
                            Id = new Guid("96687198-5cd9-4cc5-a972-d91276442290"),
                            Community = " Comunidad Valenciana",
                            TownName = "castellón de rugat"
                        },
                        new
                        {
                            Id = new Guid("6e544cfc-9c4b-439a-b4b6-bb2a74dd62d0"),
                            Community = " Comunidad Valenciana",
                            TownName = "castellonet"
                        },
                        new
                        {
                            Id = new Guid("ef862563-a286-49aa-9f16-19a3810749e6"),
                            Community = " Comunidad Valenciana",
                            TownName = "castielfabib"
                        },
                        new
                        {
                            Id = new Guid("537342e0-3a47-42ce-8352-a838d3dfe0ed"),
                            Community = " Comunidad Valenciana",
                            TownName = "catadau"
                        },
                        new
                        {
                            Id = new Guid("f5bd89b2-f4cb-492c-8ea3-697c985b5bc3"),
                            Community = " Comunidad Valenciana",
                            TownName = "catarroja"
                        },
                        new
                        {
                            Id = new Guid("7eff3718-309f-4f25-906e-1d473ae37f1e"),
                            Community = " Comunidad Valenciana",
                            TownName = "caudete de las fuentes"
                        },
                        new
                        {
                            Id = new Guid("34971ece-6135-4c9f-88e5-90b2a878d941"),
                            Community = " Comunidad Valenciana",
                            TownName = "cerdá"
                        },
                        new
                        {
                            Id = new Guid("fbb2ed60-e633-442d-878f-337d6d34f177"),
                            Community = " Comunidad Valenciana",
                            TownName = "chella"
                        },
                        new
                        {
                            Id = new Guid("d52cd3a4-00fc-43f8-b436-fc29f6df73ae"),
                            Community = " Comunidad Valenciana",
                            TownName = "chelva"
                        },
                        new
                        {
                            Id = new Guid("30bd26e1-74ea-4d25-835a-7d053da28856"),
                            Community = " Comunidad Valenciana",
                            TownName = "chera"
                        },
                        new
                        {
                            Id = new Guid("70090a72-76e6-49bc-a0a5-1651b6668acb"),
                            Community = " Comunidad Valenciana",
                            TownName = "cheste"
                        },
                        new
                        {
                            Id = new Guid("245143d3-fc04-44b9-b197-17c63e4568d1"),
                            Community = " Comunidad Valenciana",
                            TownName = "chirivella"
                        },
                        new
                        {
                            Id = new Guid("f0939e85-f8c1-4b59-97bc-66594c8eb35b"),
                            Community = " Comunidad Valenciana",
                            TownName = "chiva"
                        },
                        new
                        {
                            Id = new Guid("f4468327-e6fa-44f0-8f41-25b7d862a37d"),
                            Community = " Comunidad Valenciana",
                            TownName = "chulilla"
                        },
                        new
                        {
                            Id = new Guid("427d4445-101b-4619-a6f6-19ec6346f53f"),
                            Community = " Comunidad Valenciana",
                            TownName = "cofrentes"
                        },
                        new
                        {
                            Id = new Guid("fd8cfa02-9228-4bc8-86e9-84e18c2c129e"),
                            Community = " Comunidad Valenciana",
                            TownName = "corbera"
                        },
                        new
                        {
                            Id = new Guid("83707b67-2ee3-4d00-ae35-12c6bfe974f5"),
                            Community = " Comunidad Valenciana",
                            TownName = "cortes de pallás"
                        },
                        new
                        {
                            Id = new Guid("da1e70f7-79eb-4b0a-a471-28769fb153d7"),
                            Community = " Comunidad Valenciana",
                            TownName = "cotes"
                        },
                        new
                        {
                            Id = new Guid("1705dff6-5010-4004-8559-358b3f5bdec8"),
                            Community = " Comunidad Valenciana",
                            TownName = "cuart de les valls"
                        },
                        new
                        {
                            Id = new Guid("6a1b99cc-8da0-4798-bad4-553478949a04"),
                            Community = " Comunidad Valenciana",
                            TownName = "cuart de poblet"
                        },
                        new
                        {
                            Id = new Guid("5f155eff-7555-405a-9a4f-a9271c42b574"),
                            Community = " Comunidad Valenciana",
                            TownName = "cuartell"
                        },
                        new
                        {
                            Id = new Guid("6c0d43b3-085f-4465-9929-47b25bec8498"),
                            Community = " Comunidad Valenciana",
                            TownName = "cuatretonda"
                        },
                        new
                        {
                            Id = new Guid("c0437d07-89c8-476c-a517-f96d67ffc30e"),
                            Community = " Comunidad Valenciana",
                            TownName = "cullera"
                        },
                        new
                        {
                            Id = new Guid("6c11e225-0066-474a-a0ec-1e0b2e76794a"),
                            Community = " Comunidad Valenciana",
                            TownName = "daimuz"
                        },
                        new
                        {
                            Id = new Guid("6958ebaa-3072-4fd4-9a9d-806e0e5594c4"),
                            Community = " Comunidad Valenciana",
                            TownName = "domeño"
                        },
                        new
                        {
                            Id = new Guid("580f3568-f213-47e5-9fa5-8e543efb0b41"),
                            Community = " Comunidad Valenciana",
                            TownName = "dos aguas"
                        },
                        new
                        {
                            Id = new Guid("494fa2bc-f5ff-44da-98bf-ec2521a678a2"),
                            Community = " Comunidad Valenciana",
                            TownName = "el puig"
                        },
                        new
                        {
                            Id = new Guid("f26b79d4-4500-4328-b09b-555822650cc8"),
                            Community = " Comunidad Valenciana",
                            TownName = "emperador"
                        },
                        new
                        {
                            Id = new Guid("97a6006e-6cfc-4ace-bd55-f328efd7339c"),
                            Community = " Comunidad Valenciana",
                            TownName = "enguera"
                        },
                        new
                        {
                            Id = new Guid("53433edc-788d-4cbf-aa1f-380b35a90317"),
                            Community = " Comunidad Valenciana",
                            TownName = "énova"
                        },
                        new
                        {
                            Id = new Guid("9c35ab70-d6cb-4e75-867d-183b2b381920"),
                            Community = " Comunidad Valenciana",
                            TownName = "estivella"
                        },
                        new
                        {
                            Id = new Guid("efb5553b-e272-4d25-b8ef-95f3f53b6e17"),
                            Community = " Comunidad Valenciana",
                            TownName = "estubeny"
                        },
                        new
                        {
                            Id = new Guid("f57540b9-84af-4344-abf0-f6ba06836c5f"),
                            Community = " Comunidad Valenciana",
                            TownName = "faura"
                        },
                        new
                        {
                            Id = new Guid("eb57d985-6bd8-4428-96c7-93cf56e8df7f"),
                            Community = " Comunidad Valenciana",
                            TownName = "favareta"
                        },
                        new
                        {
                            Id = new Guid("681e1e70-ce38-42fd-9ae5-a0ede6f512b9"),
                            Community = " Comunidad Valenciana",
                            TownName = "fontanares"
                        },
                        new
                        {
                            Id = new Guid("719416a8-47f0-4f31-a2b6-f53aa1661366"),
                            Community = " Comunidad Valenciana",
                            TownName = "fortaleny"
                        },
                        new
                        {
                            Id = new Guid("68b90d73-f6b8-4b21-9d6c-1ee385bd4df3"),
                            Community = " Comunidad Valenciana",
                            TownName = "foyos"
                        },
                        new
                        {
                            Id = new Guid("1edbbdc7-8ecb-4ec9-9fce-697221092adc"),
                            Community = " Comunidad Valenciana",
                            TownName = "fuente encarroz"
                        },
                        new
                        {
                            Id = new Guid("94fcc6f2-55f1-4d56-8d44-f16ccc4dcbf7"),
                            Community = " Comunidad Valenciana",
                            TownName = "fuente la higuera"
                        },
                        new
                        {
                            Id = new Guid("2e8121aa-1564-44a6-b989-5ba782d7188e"),
                            Community = " Comunidad Valenciana",
                            TownName = "fuenterrobles"
                        },
                        new
                        {
                            Id = new Guid("15b680c9-7215-4107-98d4-7d809bf3a9c2"),
                            Community = " Comunidad Valenciana",
                            TownName = "gabarda"
                        },
                        new
                        {
                            Id = new Guid("9c006a86-6858-487b-8846-7cb9e2783325"),
                            Community = " Comunidad Valenciana",
                            TownName = "gandía"
                        },
                        new
                        {
                            Id = new Guid("499ee244-5105-4f59-a2b6-449760bb9543"),
                            Community = " Comunidad Valenciana",
                            TownName = "gátova"
                        },
                        new
                        {
                            Id = new Guid("6a1f9d48-c7cd-4f26-9bea-5f91759b30e6"),
                            Community = " Comunidad Valenciana",
                            TownName = "genovés"
                        },
                        new
                        {
                            Id = new Guid("91098712-2877-4771-9239-bf52ced81af2"),
                            Community = " Comunidad Valenciana",
                            TownName = "gestalgar"
                        },
                        new
                        {
                            Id = new Guid("105570c6-20fd-43b4-8ff1-bf19c5dfec60"),
                            Community = " Comunidad Valenciana",
                            TownName = "gilet"
                        },
                        new
                        {
                            Id = new Guid("d214c971-aa04-4041-9a7a-087dc1249aea"),
                            Community = " Comunidad Valenciana",
                            TownName = "godella"
                        },
                        new
                        {
                            Id = new Guid("d31b5a93-791c-44bf-939a-ef4711920a58"),
                            Community = " Comunidad Valenciana",
                            TownName = "godelleta"
                        },
                        new
                        {
                            Id = new Guid("49f27a9e-a146-457f-a2a2-7c8046c518de"),
                            Community = " Comunidad Valenciana",
                            TownName = "guadasequies"
                        },
                        new
                        {
                            Id = new Guid("d75e137e-b24d-4534-bf03-7f97b4ce2d41"),
                            Community = " Comunidad Valenciana",
                            TownName = "guadasuar"
                        },
                        new
                        {
                            Id = new Guid("4cff2a08-891e-4b57-9282-aed4c8af2102"),
                            Community = " Comunidad Valenciana",
                            TownName = "guardamar de la safor"
                        },
                        new
                        {
                            Id = new Guid("52f16894-faad-4917-8613-d27715291315"),
                            Community = " Comunidad Valenciana",
                            TownName = "higueruelas"
                        },
                        new
                        {
                            Id = new Guid("98ba6fa3-d109-4b5e-85b6-c288902e81ef"),
                            Community = " Comunidad Valenciana",
                            TownName = "jalance"
                        },
                        new
                        {
                            Id = new Guid("f7873a04-3e9b-4eed-9c3e-f64bd9de5199"),
                            Community = " Comunidad Valenciana",
                            TownName = "jaraco"
                        },
                        new
                        {
                            Id = new Guid("2c05a8a8-418b-44ae-9fdb-8a261b73c3b4"),
                            Community = " Comunidad Valenciana",
                            TownName = "jarafuel"
                        },
                        new
                        {
                            Id = new Guid("2ff326f5-1f81-49d0-888a-b459d6946879"),
                            Community = " Comunidad Valenciana",
                            TownName = "játiva"
                        },
                        new
                        {
                            Id = new Guid("9dfecc53-d417-4f39-9598-e4ed4fd51400"),
                            Community = " Comunidad Valenciana",
                            TownName = "jeresa"
                        },
                        new
                        {
                            Id = new Guid("5abcb3c3-dbd4-47ae-b165-559ebc74067d"),
                            Community = " Comunidad Valenciana",
                            TownName = "la alcudia"
                        },
                        new
                        {
                            Id = new Guid("4164cd95-0c9f-4ba3-a8fe-7659b6864c5a"),
                            Community = " Comunidad Valenciana",
                            TownName = "la eliana"
                        },
                        new
                        {
                            Id = new Guid("575e0992-6bcf-41b9-b3ef-0b3278da44a2"),
                            Community = " Comunidad Valenciana",
                            TownName = "la granja de la costera"
                        },
                        new
                        {
                            Id = new Guid("22c9f0da-dcaa-400b-af65-834c7df99d60"),
                            Community = " Comunidad Valenciana",
                            TownName = "la yesa"
                        },
                        new
                        {
                            Id = new Guid("a97a08e2-41b3-40c2-8362-07e3a330830e"),
                            Community = " Comunidad Valenciana",
                            TownName = "líria"
                        },
                        new
                        {
                            Id = new Guid("5470485a-2135-47a7-b8c1-272d728c2d29"),
                            Community = " Comunidad Valenciana",
                            TownName = "llanera de ranes"
                        },
                        new
                        {
                            Id = new Guid("96e24080-3394-40b2-96bc-2b9910563c14"),
                            Community = " Comunidad Valenciana",
                            TownName = "llaurí"
                        },
                        new
                        {
                            Id = new Guid("37ce3498-fd5a-481d-9bbc-ac3845a37137"),
                            Community = " Comunidad Valenciana",
                            TownName = "llombay"
                        },
                        new
                        {
                            Id = new Guid("ef8538b9-4ff1-4640-b63f-42b5d9334925"),
                            Community = " Comunidad Valenciana",
                            TownName = "llosa de ranes"
                        },
                        new
                        {
                            Id = new Guid("84b44b34-c986-4bfe-99d7-bf7280c2d50b"),
                            Community = " Comunidad Valenciana",
                            TownName = "loriguilla"
                        },
                        new
                        {
                            Id = new Guid("5ddb3184-0798-4372-a192-6853fe7b0387"),
                            Community = " Comunidad Valenciana",
                            TownName = "losa del obispo"
                        },
                        new
                        {
                            Id = new Guid("b0e3c018-ff2c-4916-913e-34803b5be7d1"),
                            Community = " Comunidad Valenciana",
                            TownName = "luchente"
                        },
                        new
                        {
                            Id = new Guid("4c245ffd-a900-4586-8d05-535ae6b189cc"),
                            Community = " Comunidad Valenciana",
                            TownName = "lugar nuevo de fenollet"
                        },
                        new
                        {
                            Id = new Guid("4399f130-d478-40dc-8472-663882661b49"),
                            Community = " Comunidad Valenciana",
                            TownName = "lugar nuevo de la corona"
                        },
                        new
                        {
                            Id = new Guid("9acec518-dcd4-4e19-ba24-8aabab4bf1d5"),
                            Community = " Comunidad Valenciana",
                            TownName = "lugar nuevo de san jerónimo"
                        },
                        new
                        {
                            Id = new Guid("fafd2b1a-0e02-40c9-84ab-cc42e3472ce0"),
                            Community = " Comunidad Valenciana",
                            TownName = "macastre"
                        },
                        new
                        {
                            Id = new Guid("ddf5741d-bb27-4375-9193-480217177f5f"),
                            Community = " Comunidad Valenciana",
                            TownName = "manises"
                        },
                        new
                        {
                            Id = new Guid("a99bff99-49d5-452a-b870-8381cbaf349e"),
                            Community = " Comunidad Valenciana",
                            TownName = "manuel"
                        },
                        new
                        {
                            Id = new Guid("541d41f2-1d48-4d59-96a4-86b959a4a034"),
                            Community = " Comunidad Valenciana",
                            TownName = "marines"
                        },
                        new
                        {
                            Id = new Guid("b956bf93-7e42-4002-bf7f-b182b23672b0"),
                            Community = " Comunidad Valenciana",
                            TownName = "masalavés"
                        },
                        new
                        {
                            Id = new Guid("13fa07f7-fab8-4067-a52b-3d72a4b65060"),
                            Community = " Comunidad Valenciana",
                            TownName = "masalfasar"
                        },
                        new
                        {
                            Id = new Guid("c3f2f59a-7d0b-4ccd-b85c-00823d3bb0ae"),
                            Community = " Comunidad Valenciana",
                            TownName = "masamagrell"
                        },
                        new
                        {
                            Id = new Guid("3885dca2-7fb8-4f54-ba33-f5ca46cfb75b"),
                            Community = " Comunidad Valenciana",
                            TownName = "masanasa"
                        },
                        new
                        {
                            Id = new Guid("cfdaf29a-ba4d-4c90-b624-3dffa6e2bd90"),
                            Community = " Comunidad Valenciana",
                            TownName = "meliana"
                        },
                        new
                        {
                            Id = new Guid("c167b944-fda3-4a8c-a2dc-f5fa595bb7c9"),
                            Community = " Comunidad Valenciana",
                            TownName = "millares"
                        },
                        new
                        {
                            Id = new Guid("6f828e0c-75ca-4062-8fac-b559ded2f125"),
                            Community = " Comunidad Valenciana",
                            TownName = "miramar"
                        },
                        new
                        {
                            Id = new Guid("47e4ac16-031a-403b-9945-78c9af0345fd"),
                            Community = " Comunidad Valenciana",
                            TownName = "mislata"
                        },
                        new
                        {
                            Id = new Guid("1d876f35-f321-49ad-9aab-297e6346ff94"),
                            Community = " Comunidad Valenciana",
                            TownName = "mogente"
                        },
                        new
                        {
                            Id = new Guid("f4f234d2-27b9-41dd-93a3-788bf2727ba8"),
                            Community = " Comunidad Valenciana",
                            TownName = "moncada"
                        },
                        new
                        {
                            Id = new Guid("e498984e-cbb0-4c68-9a05-ccc29a62b779"),
                            Community = " Comunidad Valenciana",
                            TownName = "montaberner"
                        },
                        new
                        {
                            Id = new Guid("e408da6f-6f03-4a48-9979-87616992ce45"),
                            Community = " Comunidad Valenciana",
                            TownName = "montesa"
                        },
                        new
                        {
                            Id = new Guid("82a2ee7d-0489-4129-9032-aafbf7645f46"),
                            Community = " Comunidad Valenciana",
                            TownName = "montichelvo"
                        },
                        new
                        {
                            Id = new Guid("ea71bc06-fc94-4297-b5e1-226e0f23f0e5"),
                            Community = " Comunidad Valenciana",
                            TownName = "montroy"
                        },
                        new
                        {
                            Id = new Guid("b1f9ba50-1ea4-4daa-83e6-d0b73850619c"),
                            Community = " Comunidad Valenciana",
                            TownName = "montserrat"
                        },
                        new
                        {
                            Id = new Guid("7369aaac-a350-4413-a27c-5b03054f917c"),
                            Community = " Comunidad Valenciana",
                            TownName = "museros"
                        },
                        new
                        {
                            Id = new Guid("2fbaebda-d34e-43f8-8300-87d65139beea"),
                            Community = " Comunidad Valenciana",
                            TownName = "náquera"
                        },
                        new
                        {
                            Id = new Guid("d271e7ce-6c90-4010-a594-b9bedb74cbbb"),
                            Community = " Comunidad Valenciana",
                            TownName = "navarrés"
                        },
                        new
                        {
                            Id = new Guid("4755899f-dd37-4064-9ac7-1a1501a0b370"),
                            Community = " Comunidad Valenciana",
                            TownName = "novelé"
                        },
                        new
                        {
                            Id = new Guid("59f1d4e8-0c23-497e-b51c-fb2b805c0100"),
                            Community = " Comunidad Valenciana",
                            TownName = "oliva"
                        },
                        new
                        {
                            Id = new Guid("6bdb78f9-4851-4d62-aef0-110d8ab60de2"),
                            Community = " Comunidad Valenciana",
                            TownName = "ollería"
                        },
                        new
                        {
                            Id = new Guid("2c76f35b-c87a-47cf-b83a-79594c95c0ae"),
                            Community = " Comunidad Valenciana",
                            TownName = "olocau"
                        },
                        new
                        {
                            Id = new Guid("41bef719-940c-44a7-95e4-c24b0bc06b06"),
                            Community = " Comunidad Valenciana",
                            TownName = "onteniente"
                        },
                        new
                        {
                            Id = new Guid("ceb3a92a-9c71-4c68-93b8-f7e4e9f608d1"),
                            Community = " Comunidad Valenciana",
                            TownName = "otos"
                        },
                        new
                        {
                            Id = new Guid("df1dcb3a-4e0e-4202-bc4b-40a669a5bd19"),
                            Community = " Comunidad Valenciana",
                            TownName = "paiporta"
                        },
                        new
                        {
                            Id = new Guid("dc86168e-861a-46dd-9b34-2eb7762a2fee"),
                            Community = " Comunidad Valenciana",
                            TownName = "palma de gandía"
                        },
                        new
                        {
                            Id = new Guid("144f51a7-7efb-4441-bff2-66e6a3de1417"),
                            Community = " Comunidad Valenciana",
                            TownName = "palmera"
                        },
                        new
                        {
                            Id = new Guid("345a84b6-30a6-4d92-8733-110459e86ef2"),
                            Community = " Comunidad Valenciana",
                            TownName = "palomar"
                        },
                        new
                        {
                            Id = new Guid("2b898b7e-2a8a-4eab-912e-364062c46bae"),
                            Community = " Comunidad Valenciana",
                            TownName = "paterna"
                        },
                        new
                        {
                            Id = new Guid("7c693936-d090-4d62-acb1-0955c9f575d1"),
                            Community = " Comunidad Valenciana",
                            TownName = "pedralba"
                        },
                        new
                        {
                            Id = new Guid("068c3ef6-dfaf-41b2-8ce8-8eafb43e95e0"),
                            Community = " Comunidad Valenciana",
                            TownName = "petrés"
                        },
                        new
                        {
                            Id = new Guid("f9bf7790-4aba-4c88-977e-43d1653c47f2"),
                            Community = " Comunidad Valenciana",
                            TownName = "picaña"
                        },
                        new
                        {
                            Id = new Guid("48635b15-e51d-4a53-b3d2-5e37cef8714c"),
                            Community = " Comunidad Valenciana",
                            TownName = "picasent"
                        },
                        new
                        {
                            Id = new Guid("955828bb-e864-4504-b163-3ffdf16a79d8"),
                            Community = " Comunidad Valenciana",
                            TownName = "piles"
                        },
                        new
                        {
                            Id = new Guid("39e3c4fd-6060-492f-8212-543228a0a0d9"),
                            Community = " Comunidad Valenciana",
                            TownName = "pinet"
                        },
                        new
                        {
                            Id = new Guid("97e7938d-d8c1-4eab-9675-82f5d0c90c45"),
                            Community = " Comunidad Valenciana",
                            TownName = "poliñá de júcar"
                        },
                        new
                        {
                            Id = new Guid("7e2e6fd3-3fe9-411d-abd4-bc50916d1ecd"),
                            Community = " Comunidad Valenciana",
                            TownName = "potríes"
                        },
                        new
                        {
                            Id = new Guid("850c7ca0-6d48-4a3a-9460-fb7fc1fcfc27"),
                            Community = " Comunidad Valenciana",
                            TownName = "puebla de farnals"
                        },
                        new
                        {
                            Id = new Guid("b45247ce-f5d2-44d3-94d3-6c93ade6d66a"),
                            Community = " Comunidad Valenciana",
                            TownName = "puebla de san miguel"
                        },
                        new
                        {
                            Id = new Guid("741f6ef5-c6a4-4bbf-b744-f65b039cc40d"),
                            Community = " Comunidad Valenciana",
                            TownName = "puebla de vallbona"
                        },
                        new
                        {
                            Id = new Guid("67c042e6-11fc-4743-934f-44e9e8dd858e"),
                            Community = " Comunidad Valenciana",
                            TownName = "puebla del duc"
                        },
                        new
                        {
                            Id = new Guid("aab41ec8-6068-499d-9a65-aa635c4dc027"),
                            Community = " Comunidad Valenciana",
                            TownName = "puebla larga"
                        },
                        new
                        {
                            Id = new Guid("ce641785-b363-4927-93a3-f1aec39aeb54"),
                            Community = " Comunidad Valenciana",
                            TownName = "puzol"
                        },
                        new
                        {
                            Id = new Guid("2bc46324-c059-4468-a00e-f56ed0d94c3f"),
                            Community = " Comunidad Valenciana",
                            TownName = "quesa"
                        },
                        new
                        {
                            Id = new Guid("01324847-fa45-4bb1-ab26-c678d9af2e58"),
                            Community = " Comunidad Valenciana",
                            TownName = "rafelbuñol"
                        },
                        new
                        {
                            Id = new Guid("f37d0b59-a85c-4762-a54c-abcd159865bc"),
                            Community = " Comunidad Valenciana",
                            TownName = "rafelcofer"
                        },
                        new
                        {
                            Id = new Guid("40030518-f8d4-4039-891b-9a1b9c28d9ee"),
                            Community = " Comunidad Valenciana",
                            TownName = "rafelguaraf"
                        },
                        new
                        {
                            Id = new Guid("b67f783a-639b-4a13-a750-eb029c739759"),
                            Community = " Comunidad Valenciana",
                            TownName = "ráfol de salem"
                        },
                        new
                        {
                            Id = new Guid("571e7e3d-5dfd-4ec5-aa90-b709f05d3d6a"),
                            Community = " Comunidad Valenciana",
                            TownName = "real"
                        },
                        new
                        {
                            Id = new Guid("805d8131-dbb6-4ebc-bde0-f7a962555187"),
                            Community = " Comunidad Valenciana",
                            TownName = "real de gandía"
                        },
                        new
                        {
                            Id = new Guid("754f43bb-a340-4ecc-9f6d-69624045fa2d"),
                            Community = " Comunidad Valenciana",
                            TownName = "requena"
                        },
                        new
                        {
                            Id = new Guid("6fc772af-baf9-44da-b58c-554f3b3b3186"),
                            Community = " Comunidad Valenciana",
                            TownName = "ribarroja del turia"
                        },
                        new
                        {
                            Id = new Guid("b089f329-4b2f-43cf-8295-49dc30e81fc4"),
                            Community = " Comunidad Valenciana",
                            TownName = "riola"
                        },
                        new
                        {
                            Id = new Guid("e324d66e-5c70-4526-8e24-bd8e1cf4f647"),
                            Community = " Comunidad Valenciana",
                            TownName = "rocafort"
                        },
                        new
                        {
                            Id = new Guid("155181c1-e7a8-4250-bd2d-f84e105ee1ca"),
                            Community = " Comunidad Valenciana",
                            TownName = "rotglá y corberà"
                        },
                        new
                        {
                            Id = new Guid("5339a698-9487-4cda-b32b-fe4ecf19a0c8"),
                            Community = " Comunidad Valenciana",
                            TownName = "rótova"
                        },
                        new
                        {
                            Id = new Guid("9b3a1cba-a066-4f1a-a711-bf0794645e3a"),
                            Community = " Comunidad Valenciana",
                            TownName = "rugat"
                        },
                        new
                        {
                            Id = new Guid("4a978b5c-9c88-4b1c-92fa-ee27f68af818"),
                            Community = " Comunidad Valenciana",
                            TownName = "sagunto"
                        },
                        new
                        {
                            Id = new Guid("b78fda29-84ca-4cf3-a5cf-4fa54cb1d38d"),
                            Community = " Comunidad Valenciana",
                            TownName = "salem"
                        },
                        new
                        {
                            Id = new Guid("076072f5-2db3-41db-b428-6e568130478a"),
                            Community = " Comunidad Valenciana",
                            TownName = "san antonio de benagéber"
                        },
                        new
                        {
                            Id = new Guid("a3a5c73b-d048-40a1-8efd-04cdb3e9552e"),
                            Community = " Comunidad Valenciana",
                            TownName = "san juan de énova"
                        },
                        new
                        {
                            Id = new Guid("981b4475-12af-4c33-8365-1bcba5973145"),
                            Community = " Comunidad Valenciana",
                            TownName = "sedaví"
                        },
                        new
                        {
                            Id = new Guid("d1399795-5a9a-4ae9-9e30-bed2ddaf05a5"),
                            Community = " Comunidad Valenciana",
                            TownName = "segart"
                        },
                        new
                        {
                            Id = new Guid("52ad3fd1-8e21-4677-8a7e-0951c9365f7d"),
                            Community = " Comunidad Valenciana",
                            TownName = "sellent"
                        },
                        new
                        {
                            Id = new Guid("2ea54269-9476-43be-a067-05e65ef22a5d"),
                            Community = " Comunidad Valenciana",
                            TownName = "sempere"
                        },
                        new
                        {
                            Id = new Guid("5687d155-6613-40c1-bb8d-d65e767860b9"),
                            Community = " Comunidad Valenciana",
                            TownName = "señera"
                        },
                        new
                        {
                            Id = new Guid("43b31003-4633-495c-8331-c83834959e1f"),
                            Community = " Comunidad Valenciana",
                            TownName = "serra"
                        },
                        new
                        {
                            Id = new Guid("54aaf3de-87c2-4b08-b1fa-56555aa75b38"),
                            Community = " Comunidad Valenciana",
                            TownName = "siete aguas"
                        },
                        new
                        {
                            Id = new Guid("b247da68-700b-481c-b880-3b5c5a1f2729"),
                            Community = " Comunidad Valenciana",
                            TownName = "silla"
                        },
                        new
                        {
                            Id = new Guid("6e1b601d-5836-4832-8427-ffa5d6895943"),
                            Community = " Comunidad Valenciana",
                            TownName = "simat de valldigna"
                        },
                        new
                        {
                            Id = new Guid("9de5516f-9500-4c57-a616-e8ee7213fa19"),
                            Community = " Comunidad Valenciana",
                            TownName = "sinarcas"
                        },
                        new
                        {
                            Id = new Guid("3a87f18c-0cf7-4c29-91b8-299f02c97202"),
                            Community = " Comunidad Valenciana",
                            TownName = "sollana"
                        },
                        new
                        {
                            Id = new Guid("bac8e02b-3507-473c-8d11-6c75190daa1c"),
                            Community = " Comunidad Valenciana",
                            TownName = "sot de chera"
                        },
                        new
                        {
                            Id = new Guid("97852ef0-8c30-4b24-b5b1-737f44ef751c"),
                            Community = " Comunidad Valenciana",
                            TownName = "sueca"
                        },
                        new
                        {
                            Id = new Guid("1d6c2d03-5345-4d63-846a-0ad055f813cd"),
                            Community = " Comunidad Valenciana",
                            TownName = "sumacárcel"
                        },
                        new
                        {
                            Id = new Guid("0ed5ff46-d70c-403f-81b2-a84fb4be7190"),
                            Community = " Comunidad Valenciana",
                            TownName = "tabernes blanques"
                        },
                        new
                        {
                            Id = new Guid("49067672-052c-48b3-8e64-913cd6803c66"),
                            Community = " Comunidad Valenciana",
                            TownName = "tabernes de valldigna"
                        },
                        new
                        {
                            Id = new Guid("510248ab-797d-4e18-bb20-ad78aa900553"),
                            Community = " Comunidad Valenciana",
                            TownName = "teresa de cofrentes"
                        },
                        new
                        {
                            Id = new Guid("22030132-4c62-4250-8d65-6d85e5ca4ad1"),
                            Community = " Comunidad Valenciana",
                            TownName = "terrateig"
                        },
                        new
                        {
                            Id = new Guid("f8f57c8b-cc29-4618-941d-704a9773ed52"),
                            Community = " Comunidad Valenciana",
                            TownName = "titaguas"
                        },
                        new
                        {
                            Id = new Guid("0328d588-2f62-4a4b-8e2b-f0d1149e4c7a"),
                            Community = " Comunidad Valenciana",
                            TownName = "torrebaja"
                        },
                        new
                        {
                            Id = new Guid("7f814d62-4b46-4f66-a7d4-42f53d372d94"),
                            Community = " Comunidad Valenciana",
                            TownName = "torrella"
                        },
                        new
                        {
                            Id = new Guid("44cc929b-9494-4249-9a52-154042c1b348"),
                            Community = " Comunidad Valenciana",
                            TownName = "torrente"
                        },
                        new
                        {
                            Id = new Guid("d9aff0f3-35bb-46f5-a028-db7c44b061fe"),
                            Community = " Comunidad Valenciana",
                            TownName = "torres torres"
                        },
                        new
                        {
                            Id = new Guid("37395cd3-a350-487b-86f3-0993df3f8aad"),
                            Community = " Comunidad Valenciana",
                            TownName = "tous"
                        },
                        new
                        {
                            Id = new Guid("15607528-1f10-47af-b3ed-22eb5942ede2"),
                            Community = " Comunidad Valenciana",
                            TownName = "tuéjar"
                        },
                        new
                        {
                            Id = new Guid("942a987b-2875-42ac-8bb5-cf37ab71db5d"),
                            Community = " Comunidad Valenciana",
                            TownName = "turís"
                        },
                        new
                        {
                            Id = new Guid("1c1776ec-b828-4bad-baf6-f942c1107ef8"),
                            Community = " Comunidad Valenciana",
                            TownName = "utiel"
                        },
                        new
                        {
                            Id = new Guid("d7dad211-13ed-4b32-aebf-7060f81040e4"),
                            Community = " Comunidad Valenciana",
                            TownName = "vallada"
                        },
                        new
                        {
                            Id = new Guid("f0e6eedd-6354-4654-9bc7-f84372bf7587"),
                            Community = " Comunidad Valenciana",
                            TownName = "vallanca"
                        },
                        new
                        {
                            Id = new Guid("7a668df6-bdba-4ddb-83c0-7f26ea01986b"),
                            Community = " Comunidad Valenciana",
                            TownName = "vallés"
                        },
                        new
                        {
                            Id = new Guid("bfb02abf-0dd5-412d-b969-b8d40382ef34"),
                            Community = " Comunidad Valenciana",
                            TownName = "venta del moro"
                        },
                        new
                        {
                            Id = new Guid("bfb69b27-937b-4faf-9aeb-13c0e30b0f42"),
                            Community = " Comunidad Valenciana",
                            TownName = "villalonga"
                        },
                        new
                        {
                            Id = new Guid("6b6fc680-a1a5-40ed-99f9-3b07776b8403"),
                            Community = " Comunidad Valenciana",
                            TownName = "villamarchante"
                        },
                        new
                        {
                            Id = new Guid("8464183b-dfec-44ad-8ed3-2954ddd01530"),
                            Community = " Comunidad Valenciana",
                            TownName = "villanueva de castellón"
                        },
                        new
                        {
                            Id = new Guid("8f8e2329-1867-4858-a5a0-30be865ae636"),
                            Community = " Comunidad Valenciana",
                            TownName = "villar del arzobispo"
                        },
                        new
                        {
                            Id = new Guid("0b4b54fc-f83d-43b0-8355-447bbb6a4726"),
                            Community = " Comunidad Valenciana",
                            TownName = "villargordo del cabriel"
                        },
                        new
                        {
                            Id = new Guid("ceb64fb7-476f-408c-b678-8f36baa9a277"),
                            Community = " Comunidad Valenciana",
                            TownName = "vinalesa"
                        },
                        new
                        {
                            Id = new Guid("32b6a538-5eb6-4df8-a08c-a068dc99bfaf"),
                            Community = " Comunidad Valenciana",
                            TownName = "yátova"
                        },
                        new
                        {
                            Id = new Guid("9bbbed71-e392-4737-bcb2-513e4090f364"),
                            Community = " Comunidad Valenciana",
                            TownName = "zarra"
                        });
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("DNI");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.UserTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AmountToPay")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("date");

                    b.Property<double>("BaseAmount")
                        .HasColumnType("double precision");

                    b.Property<bool>("Paid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("PaymentDeadlineDate")
                        .HasColumnType("date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<Guid>("TaxId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TownId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaxId");

                    b.HasIndex("TownId");

                    b.HasIndex("UserId");

                    b.ToTable("User_Tax");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.UserTown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TownId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TownId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("User_Town");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.UserTax", b =>
                {
                    b.HasOne("Devon4Net.WebAPI.Implementation.Domain.Entities.Tax", "Tax")
                        .WithMany("UserTaxes")
                        .HasForeignKey("TaxId")
                        .HasConstraintName("user_tax_fk_tax")
                        .IsRequired();

                    b.HasOne("Devon4Net.WebAPI.Implementation.Domain.Entities.Town", "Town")
                        .WithMany("UserTaxes")
                        .HasForeignKey("TownId")
                        .HasConstraintName("user_tax_fk_town")
                        .IsRequired();

                    b.HasOne("Devon4Net.WebAPI.Implementation.Domain.Entities.User", "User")
                        .WithMany("UserTaxes")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_tax_fk_user")
                        .IsRequired();

                    b.Navigation("Tax");

                    b.Navigation("Town");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.UserTown", b =>
                {
                    b.HasOne("Devon4Net.WebAPI.Implementation.Domain.Entities.Town", "Town")
                        .WithMany("UserTowns")
                        .HasForeignKey("TownId")
                        .HasConstraintName("user_town_fk__town")
                        .IsRequired();

                    b.HasOne("Devon4Net.WebAPI.Implementation.Domain.Entities.User", "User")
                        .WithOne("UserTown")
                        .HasForeignKey("Devon4Net.WebAPI.Implementation.Domain.Entities.UserTown", "UserId")
                        .HasConstraintName("user_town_fk_user")
                        .IsRequired();

                    b.Navigation("Town");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.Tax", b =>
                {
                    b.Navigation("UserTaxes");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.Town", b =>
                {
                    b.Navigation("UserTaxes");

                    b.Navigation("UserTowns");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.User", b =>
                {
                    b.Navigation("UserTaxes");

                    b.Navigation("UserTown");
                });
#pragma warning restore 612, 618
        }
    }
}
