// <auto-generated />
using System;
using Devon4Net.WebAPI.Implementation.Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Devon4Net.WebAPI.Implementation.Migrations
{
    [DbContext(typeof(AelContext))]
    [Migration("20210103193325_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:Collation", "en_US.utf8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.Town", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Community")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("Towns");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("DNI");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.UserTown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TownId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TownId");

                    b.HasIndex("UserId");

                    b.ToTable("User_Town");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.UserTown", b =>
                {
                    b.HasOne("Devon4Net.WebAPI.Implementation.Domain.Entities.Town", "Town")
                        .WithMany("UserTowns")
                        .HasForeignKey("TownId")
                        .HasConstraintName("user_town_fk_1")
                        .IsRequired();

                    b.HasOne("Devon4Net.WebAPI.Implementation.Domain.Entities.User", "User")
                        .WithMany("UserTowns")
                        .HasForeignKey("UserId")
                        .HasConstraintName("user_town_fk")
                        .IsRequired();

                    b.Navigation("Town");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.Town", b =>
                {
                    b.Navigation("UserTowns");
                });

            modelBuilder.Entity("Devon4Net.WebAPI.Implementation.Domain.Entities.User", b =>
                {
                    b.Navigation("UserTowns");
                });
#pragma warning restore 612, 618
        }
    }
}
