version: '3'
services:
  ael:
    build:
      context: .
      dockerfile: ael.dockerfile    
    ports:
      - "8085:8085"
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres
    ports:
      - "5902:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=postgres